################################################################################
# File : gpio.toml
# Auth : David Gussler
# ==============================================================================
# Shrikebyte VHDL Library - https://github.com/shrikebyte/sblib
# Copyright (C) Shrikebyte, LLC
# Licensed under the Apache 2.0 license, see LICENSE for details.
# ==============================================================================
# Registers for the GPIO (General Purpose Input Output) module
################################################################################


################################################################################
[isr]
description = "Interrupt Status Register"
mode = "r_wpulse"

isr.type = "bit_vector"
isr.width = 32
isr.description = """
The Interrupt Status Register uses one bit to represent each interrupt
condition. When an interrupt condition occurs, it is immediately latched in
this register. The latched interrupt condition is cleared by writing a 1 to its
corresponding bit position. Writing a 1 to a bit position that is 0 has no
effect. Likewise, writing a 0 to a bit location that is 1 has no effect.
Multiple bits can be cleared with a single write.

For any bit set in the Interrupt Status Register, a corresponding bit must also
be set in the Interrupt Enable Register for the interrupt signal to be driven
active-high out of the module. The Interrupt Status Register is not affected
by the Interrupt Enable Register. The Interrupt Enable Register only enables or
disables the module's interrupt output signal.

Read definition for each bit:

* 0 = No interrupt has occurred
* 1 = Interrupt has occurred

Write definition for each bit:

* 0 = No effect
* 1 = Clear interrupt status

For the GPIO module,
an interrupt is latched for a specific bit's input if
a 0->1 or 1->0 transition is detected.
"""


################################################################################
[ier]
description = "Interrupt Enable Register"
mode = "r_w"

ier.type = "bit_vector"
ier.width = 32
ier.description = """
Read & write definition for each bit:

* 0 = Disable interrupt
* 1 = Enable interrupt
"""


################################################################################
[dout]
description = "Output Data Register"
mode = "r_wpulse"

dout.type = "bit_vector"
dout.width = 32
dout.description = """
Data written to this register is output at the GPIO channel's output port.

The default value of this register is hard-coded by the FPGA. Ignore the generic
default value given in this register description (it is overridden in the FPGA).
Additional documentation must be provided by the firmware designer that gives
the true default value and for the mapping of these register bits to FPGA
signals, because these settings could change for different firmware builds.
"""

################################################################################
[din]
mode = "r"
description = "Input Data Register"

din.type = "bit_vector"
din.width = 32
din.description = """
Reads to this register return the data present at the GPIO channel's input port.

Additional documentation must be provided by the firmware designer that gives
the mapping of these register bits to FPGA
signals, because these settings could change for different firmware builds.
"""

################################################################################
[tri]
mode = "r_wpulse"
description = "Tri-state (Input) Enable Register"

tri.type = "bit_vector"
tri.width = 32
tri.description = """
Read & write definition for each bit:

* 0 = Configure pin as output
* 1 = Configure pin as input

The default value of this register is hard-coded by the FPGA. Ignore the generic
default value given in this register description (it is overridden in the FPGA).
Additional documentation must be provided by the firmware designer that gives
the true default value and for the mapping of these register bits to FPGA
signals, because these settings could change for different firmware builds.
"""
