################################################################################
# File : stdver.toml
# Auth : David Gussler
# ==============================================================================
# Shrikebyte VHDL Library - https://github.com/shrikebyte/sblib
# Copyright (C) Shrikebyte, LLC
# Licensed under the Apache 2.0 license, see LICENSE for details.
# ==============================================================================
# Registers for the stdver, Standard Version, module. These registers
# should be instantiated at the base address of an FPGA design.
################################################################################


################################################################################
[scratchpad]
description = "Scratchpad Register"
mode = "r_w"

scratchpad.type = "bit_vector"
scratchpad.width = 32
scratchpad.default_value = 0x12345678
scratchpad.description = """
Scratchpad that may be used for testing FPGA register access.
"""


################################################################################
[id]
description = "ID Register"
mode = "r"

id.type = "bit_vector"
id.width = 32
id.description = """
Unique identification number for this fpga.
"""


################################################################################
[version]
description = "Version Register"
mode = "r"

patch.type = "integer"
patch.max_value = 255
patch.description = "Patch - Backward compatible bug fix."

minor.type = "integer"
minor.max_value = 255
minor.description = "Minor - Backward compatible new feature."

major.type = "integer"
major.max_value = 255
major.description = "Major - Incompatible change."

engr.type = "bit_vector"
engr.width = 4
engr.description = """
* 0x0 = Official release build.
* 0xE = Engineering test build.
"""

dirty.type = "bit_vector"
dirty.width = 4
dirty.description = """
* 0x0 = FPGA was built from a clean repository.
* 0xD = FPGA was built from modified source files that were not checked in to git.
"""


################################################################################
[date]
description = "Build Date Register in BCD format 0xYYYYMMDD"
mode = "r"

day.type = "bit_vector"
day.width = 8
day.description = "Build Day (0 to 31)."

month.type = "bit_vector"
month.width = 8
month.description = "Build Month (0 to 12)."

year.type = "bit_vector"
year.width = 16
year.description = "Build Year (0 to 9999)."


################################################################################
[time]
description = "Build Time Register in BCD format 0xHHMMSS"
mode = "r"

second.type = "bit_vector"
second.width = 8
second.description = "Build Second (0 to 59)."

minute.type = "bit_vector"
minute.width = 8
minute.description = "Build Minute (0 to 59)."

hour.type = "bit_vector"
hour.width = 8
hour.description = "Build Hour (0 to 23)."


################################################################################
[githash]
description = "Git Hash Register"
mode = "r"

githash.type = "bit_vector"
githash.width = 32
githash.description = """
The 8 most significant characters of the source code's git hash used for
this build.
"""
